### ISSUE TITLE
CH340C Implementation with 5V and 3V3 Support

### ISSUE THREAD

**Issue by zwu513** [sparkfun/Serial_Basic_Breakout-CH340C#3] opened 2024-03-19 06:02 UTC
The CH340C datasheet says to connect V3 to VCC when running in 3V3 mode, but the CH340C breakout board with USB C does not implement this.

Product: https://cdn.sparkfun.com/assets/5/2/5/4/2/Serial-Basic-CH340C-and-USBC.pdf
Datasheet: https://cdn.sparkfun.com/assets/5/0/a/8/5/CH340DS1.PDF
Section 5.1
CH340 supports 5V and 3.3V power supply. When using 5V power supply, the VCC pin connects 5V power and the V3 pin should connect with a 0.1uF decoupling capacitor. When using 3.3V power supply, V3 should connect with VCC, both powered with 3.3V power supply, and the other circuit voltage which connected with CH340 cannot exceed 3.3V

**Comment by nseidle** [comment] 2024-03-19 14:43
In order to support a configurable 3.3V or 5V serial interface, we use a single solder jumper and an external 3.3V regulator. To allow for this electrically, V3 is connected to C9 for decoupling. VCC on the CH340C (pin 16) is either connected to 5V or 3.3V. At no time is V3 connected to the 5V rail. This is all within the acceptable limits of the datasheet as far as I can see. There is perhaps, an odd scenario where the external 3.3V regulator is slightly greater or less than the internal 3.3V regulator in the CH340C causing stress on one or the other regs, but in our experience, this has never been reported as an issue. Please let us know if there is behavior you are experiencing otherwise. I'm going to close this for now because it's functional and by design.

**Closed as completed by nseidle** 2024-03-19 14:43 UTC
